### ISSUE TITLE
Unwrap multiple image nodes

### ISSUE THREAD

**Issue by cedricdelpoux** [johno/remark-unwrap-images#1]
Hello, I was trying to make a gatsby plugin to unwrap images and I found your plugin. Thank you for that. What about unwrap multiple images ?

If my markdown looks like:
```
![](img1)
![](img2)
```

The generated output would be:
```
<p>
   <img />
   <img />
</p>
```

I tried 
```
visit(markdownAST, `image`, (node, index, parent) => {
    const [firstChildNode, ...childNodes] = parent.children
    parent.type = firstChildNode.type
    parent.url = firstChildNode.url
    parent.alt = firstChildNode.alt
    parent.title = firstChildNode.title
    unwrappedImagesNodes.push(parent)

    childNodes.map(childNode => {
      unwrappedImagesNodes.push(childNode)
    })
  })
```
but I did not work. I very new to AST syntax and I don't find an util to create a node beside an other node. Because I replace the parent node with the first child node. But whaut about the other ones?

**Comment by johno** [comment]
Yeah, I think what we'd need to do is check if all children in a node are images, and if they are we can slice in the images to replace the parent. We can do this by manipulating `parent.parent.children` (I think).

For now, though you can also separate the images with a newline. The rendered output will be the same as what you're desiring.

```
![](img1)

![](img2)
```

**Comment by cedricdelpoux** [comment]
Do you know how can I replace a paragraph (single node) with it's children (multiples nodes) ? I could not found
The only way I found was to set
```
parent.type = "html"
parent.value = "<img/><img />"
```
But it's not a good solution because my images are not images node anymore so I'm breaking the following plugins looking for images

**Comment by wooorm** [comment]
@johno I solved this in https://github.com/remarkjs/remark-unwrap-images/commit/0e4aa2cdabc5ff29739894e90cbafb6212326696. I updated the whole repo to reflect the rest of the ecosystem as well so instead of a PR, could you review if the current behaviour makes sense? If so, we can cut a 1.0.0!

**Comment by johno** [comment]
This lgtm! Nice work on the thorough tests. I'll add you as an owner to the package now.

**Comment by wooorm** [comment]
Great! Released! :100:
