### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by SalahAdDin** [johno/remark-unwrap-images#5]
### Subject of the feature
This package lacks to **Typescript** support despite `react-markdown` already offers support for it,

### Problem

We are trying to migrate our current portffolio from **Javascript** to **Typscript** component by component and we found the next issue related to this package:

```shell
<html>TS7016: Could not find a declaration file for module 'remark-unwrap-images'. '/home/luisalaguna/Projects/portfolio/frontend2.0/node_modules/remark-unwrap-images/index.js' implicitly has an 'any' type.<br/>Try `npm i --save-dev @types/remark-unwrap-images` if it exists or add a new declaration (.d.ts) file containing `declare module 'remark-unwrap-images';`
```

### Expected behavior

It should have a minimal typscript support.

### Alternatives

As this is a very specifical plugin, it has no other alternative.

**Comment by wooorm** [comment]
It’s a warning. Not an error. Everything’s fine.

If you do want to add support for TS, see the most recent discussion [issue](https://github.com/remarkjs/remark-unlink/issues/3) and [corresponding PR](https://github.com/remarkjs/remark-unlink/pull/4)!

**Comment by SalahAdDin** [comment]
@wooorm I'm pretty sure this is not just a warn, it is a bug:
![image](https://user-images.githubusercontent.com/5034215/121790554-43307600-cbe9-11eb-9495-b07e1227f5be.png)

**Comment by ChristianMurphy** [comment]
@SalahAdDin it is a warning, and can be ignored with `// @ts-ignore`
Or if you don't want to ignore the warning, you could open a PR adding typing as @wooorm suggests.

**Comment by SalahAdDin** [comment]
> @SalahAdDin it is a warning, and can be ignored with `// @ts-ignore`
> Or if you don't want to ignore the warning, you could open a PR adding typing as @wooorm suggests.

Ok, let me do that tomorrow.

Thank you.
