### ISSUE TITLE
Support unwrapping for MDX nodes

### ISSUE THREAD

**Issue by viglucci** [johno/remark-unwrap-images#8]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I am attempting to leverage this plugin to unwrap image nodes represented in MDX, so that I can then leverage a plugin that will decorate the images with their size/dimensions. The enclosing `<p>` tag around the images causes the later plugin to not match on the image.

### Solution

MDX images should be unwrapped from their enclosing `<p>` tags.

For `MDX` the `child.type` is `mdxJsxTextElement`, which fails the current conditional check. Additionally, the `child` object contains an additional `name` property which is set to `img`.

The conditional could be updated as so to cover this case:

```js
if (
  child.type === 'image' ||
  child.type === 'imageReference' ||
  (child.type === 'mdxJsxTextElement' && child.name === 'img')) {
  image = containsImage
}
```

### Alternatives

The plugin could be updated to support configuration so that the user could provide an additional function to `applicable` so that they could control which nodes additional match the check.

**Comment by wooorm** [comment]
Thanks for your patience! I’ve been a bit preoccupied with war.
As I understand it, you practically mean JSX nodes, that use `<img>` tags, correct?

While that is possible, I wonder whether it’s correct. MDX is *agnostic* to HTML semantics (it could be used with React Native, terminals, or many other things), and what about custom image components (`next/image`? `MyImage`?) as well? So maybe hardcoding `img` isn’t great.

From your statement:

> The enclosing `<p>` tag around the images causes the later plugin to not match on the image.

I’m also wondering: perhaps that later plugin can be improved?

> `mdxJsxTextElement`

In many cases, `mdxJsxFlowElement` is used instead, and you wouldn’t even have this problem 🤔 Your problem doesn’t exist when you do:

```jsx
Lorem

<img />

Ipsum.
```

^-- there is no paragraph there. So how *are* you even getting those paragraphs?
