### ISSUE TITLE
The plugin produces invalid AST

### ISSUE THREAD

**Issue by marekdedic** [johno/remark-unwrap-images#9]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.0.1

### Steps to reproduce

```ts
import { unified } from "https://cdn.jsdelivr.net/npm/unified@10.1.2/+esm";
import remarkParse from "https://cdn.jsdelivr.net/npm/remark-parse@10.0.1/+esm";
import remarkUnwrapImages from "https://cdn.jsdelivr.net/npm/remark-unwrap-images@3.0.1/+esm";

const sourceMarkdown =
  '![Minion](https://octodex.github.com/images/minion.png)\n![Stormtroopocat](https://octodex.github.com/images/stormtroopocat.jpg "The Stormtroopocat")\n\n';

async function main() {
  document.querySelector("#source").textContent = sourceMarkdown;

  const remark = unified().use(remarkParse).use(remarkUnwrapImages)

  const file = remark.runSync(remark.parse(sourceMarkdown));

  document.querySelector("#result").textContent = JSON.stringify(file, undefined, 2);
  document.querySelector("#error").textContent = "";
}

main().catch((error) => {
  document.querySelector("#error").textContent = error;
});
```

I would link a codesandbox, but I couldn't figure out how to actually run the code I put in - there is no "run" button anywhere :shrug: 

### Expected behavior

The AST should be something like

- Root
  - Image
  - Image

or

- Root
  - Image
  - Paragraph
    - Text
  - Image

### Actual behavior

The ASP look like

- Root
  - Image
  - Text
  - Image

i.e., it places `Text` directly in `Root`, which is prohibited in `mdast` as per the [content model](https://github.com/syntax-tree/mdast#content-model)

### Runtime

Other (please specify in steps to reproduce)

### Package manager

npm 8

### OS

Linux

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
Why do you believe image can be there? And text can't?

Yes: the entire project produces "invalid" ASTs. Images are not supposed to be next to paragraphs.

This project is very old. It's probably better to make a rehype version of this and depreciate it.

**Comment by marekdedic** [comment]
Hmm, that's actually an excellent point, thanks. I solve the issue by not using this plugin at all :D
